services:
  - type: web
    name: ian-avatar
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_HEYGEN_API_KEY
        value: ZTRjM2RiMTc2YzYwNDdiZGJlMTgzYmQwMzI5YmU4YmItMTc0MDQzNDc4MA==
      - key: NEXT_PUBLIC_N8N_WEBHOOK_URL
        value: https://shlomonm.app.n8n.cloud/webhook-test/2afff6a8-4194-4a79-bcb0-73c9dd4dc18b
      - key: NODE_VERSION
        value: 18.17.0
